// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1RE0GQ8nCFsgW4KXwenPjJ8qkA4QSVPs',
    appId: '1:673618824191:web:949d9bc63351afb8fe75ca',
    messagingSenderId: '673618824191',
    projectId: 'pth220104',
    authDomain: 'pth220104.firebaseapp.com',
    storageBucket: 'pth220104.firebasestorage.app',
    measurementId: 'G-B8LHL0YL3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNmwyl0uHJe3Mxg-cuYzSamI-S1kiJzz4',
    appId: '1:673618824191:android:cde3ba3e18dcecdbfe75ca',
    messagingSenderId: '673618824191',
    projectId: 'pth220104',
    storageBucket: 'pth220104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1RYYWy5QmPJH_PKW7kNcb_xV3BqNaofU',
    appId: '1:673618824191:ios:2057001e8d39d74ffe75ca',
    messagingSenderId: '673618824191',
    projectId: 'pth220104',
    storageBucket: 'pth220104.firebasestorage.app',
    iosBundleId: 'com.example.appMobileFlutter',
  );
}
